"""add i13 delayed recovery claims

Revision ID: 350391c65e38
Revises: b1e89ccdb30a
Create Date: 2026-09-27 10:44:52.791197

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "350391c65e38"
down_revision: Union[str, None] = "b1e89ccdb30a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aeterna_recovery_audit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("recovery_id", sa.UUID(), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("grant_id", sa.UUID(), nullable=True),
        sa.Column("request_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('record.provisioned', 'record.confirmed', 'record.abandoned', 'grant.created', 'claim.started', 'claim.verified', 'secret.released')",
            name="ck_aeterna_recovery_audit_event_type",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aeterna_recovery_audit_account_id"),
        "aeterna_recovery_audit",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aeterna_recovery_audit_contact_id"),
        "aeterna_recovery_audit",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aeterna_recovery_audit_recovery_id"),
        "aeterna_recovery_audit",
        ["recovery_id"],
        unique=False,
    )
    op.create_table(
        "aeterna_recovery_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("encrypted_srs", sa.LargeBinary(), nullable=False),
        sa.Column("kms_provider", sa.String(length=32), nullable=False),
        sa.Column("kms_key_arn", sa.String(length=512), nullable=False),
        sa.Column("kms_key_material_id", sa.String(length=512), nullable=False),
        sa.Column("kms_context_version", sa.Integer(), nullable=False),
        sa.Column("crypto_format_version", sa.Integer(), nullable=False),
        sa.Column("recovery_context_version", sa.Integer(), nullable=False),
        sa.Column("wrapper_digest", sa.LargeBinary(), nullable=True),
        sa.Column("provision_request_id", sa.UUID(), nullable=False),
        sa.Column("provision_request_digest", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("abandoned_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state = 'pending_confirmation' AND wrapper_digest IS NULL AND confirmed_at IS NULL AND abandoned_at IS NULL) OR (state = 'sealed' AND wrapper_digest IS NOT NULL AND confirmed_at IS NOT NULL AND abandoned_at IS NULL) OR (state IN ('abandoned', 'expired') AND abandoned_at IS NOT NULL)",
            name="ck_aeterna_recovery_records_state_timestamps",
        ),
        sa.CheckConstraint(
            "state IN ('pending_confirmation', 'sealed', 'abandoned', 'expired')",
            name="ck_aeterna_recovery_records_state",
        ),
        sa.CheckConstraint(
            "octet_length(encrypted_srs) BETWEEN 1 AND 8192",
            name="ck_aeterna_recovery_records_ciphertext_length",
        ),
        sa.CheckConstraint(
            "octet_length(provision_request_digest) = 32",
            name="ck_aeterna_recovery_records_request_digest_length",
        ),
        sa.CheckConstraint(
            "wrapper_digest IS NULL OR octet_length(wrapper_digest) = 32",
            name="ck_aeterna_recovery_records_wrapper_digest_length",
        ),
        sa.CheckConstraint(
            "kms_context_version = 1 AND crypto_format_version = 1 AND recovery_context_version = 1",
            name="ck_aeterna_recovery_records_versions",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["aeterna_accounts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["aeterna_devices.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provision_request_id", name="uq_aeterna_recovery_records_provision_request"
        ),
    )
    op.create_index(
        op.f("ix_aeterna_recovery_records_account_id"),
        "aeterna_recovery_records",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aeterna_recovery_records_device_id"),
        "aeterna_recovery_records",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        "uq_aeterna_recovery_records_live_device_vault",
        "aeterna_recovery_records",
        ["account_id", "device_id", "vault_id"],
        unique=True,
        postgresql_where=sa.text("state IN ('pending_confirmation', 'sealed')"),
    )
    op.create_table(
        "aeterna_recovery_grants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("recovery_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("released_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state = 'claimed' AND claimed_at IS NOT NULL) OR (state <> 'claimed' AND claimed_at IS NULL)",
            name="ck_aeterna_recovery_grants_claimed_at",
        ),
        sa.CheckConstraint(
            "state IN ('available', 'claimed', 'revoked')",
            name="ck_aeterna_recovery_grants_state",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["aeterna_accounts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["aeterna_contacts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["recovery_id"], ["aeterna_recovery_records.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "recovery_id",
            "contact_id",
            name="uq_aeterna_recovery_grants_record_contact",
        ),
    )
    op.create_index(
        op.f("ix_aeterna_recovery_grants_account_id"),
        "aeterna_recovery_grants",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aeterna_recovery_grants_contact_id"),
        "aeterna_recovery_grants",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aeterna_recovery_grants_recovery_id"),
        "aeterna_recovery_grants",
        ["recovery_id"],
        unique=False,
    )
    op.create_table(
        "aeterna_recovery_claim_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("grant_id", sa.UUID(), nullable=False),
        sa.Column("token_digest", sa.LargeBinary(), nullable=False),
        sa.Column("token_key_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'active' AND consumed_at IS NULL) OR (status <> 'active' AND consumed_at IS NOT NULL)",
            name="ck_aeterna_recovery_claim_links_consumed_at",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'consumed', 'expired', 'revoked')",
            name="ck_aeterna_recovery_claim_links_status",
        ),
        sa.CheckConstraint(
            "octet_length(token_digest) = 32",
            name="ck_aeterna_recovery_claim_links_token_digest_length",
        ),
        sa.CheckConstraint(
            "token_key_version > 0", name="ck_aeterna_recovery_claim_links_key_version"
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"], ["aeterna_recovery_grants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "token_digest", name="uq_aeterna_recovery_claim_links_token_digest"
        ),
    )
    op.create_index(
        op.f("ix_aeterna_recovery_claim_links_grant_id"),
        "aeterna_recovery_claim_links",
        ["grant_id"],
        unique=False,
    )
    op.create_table(
        "aeterna_recovery_claim_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("grant_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("recovery_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("wrapper_digest", sa.LargeBinary(), nullable=False),
        sa.Column("token_digest", sa.LargeBinary(), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'active' AND consumed_at IS NULL) OR (status <> 'active' AND consumed_at IS NOT NULL)",
            name="ck_aeterna_recovery_claim_tokens_consumed_at",
        ),
        sa.CheckConstraint(
            "scope = 'recovery.srs.read'", name="ck_aeterna_recovery_claim_tokens_scope"
        ),
        sa.CheckConstraint(
            "status IN ('active', 'consumed', 'expired')",
            name="ck_aeterna_recovery_claim_tokens_status",
        ),
        sa.CheckConstraint(
            "octet_length(token_digest) = 32",
            name="ck_aeterna_recovery_claim_tokens_digest_length",
        ),
        sa.CheckConstraint(
            "octet_length(wrapper_digest) = 32",
            name="ck_aeterna_recovery_claim_tokens_wrapper_digest_length",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["aeterna_accounts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["aeterna_contacts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["aeterna_devices.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["grant_id"], ["aeterna_recovery_grants.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["recovery_id"], ["aeterna_recovery_records.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "token_digest", name="uq_aeterna_recovery_claim_tokens_token_digest"
        ),
    )
    op.create_index(
        op.f("ix_aeterna_recovery_claim_tokens_grant_id"),
        "aeterna_recovery_claim_tokens",
        ["grant_id"],
        unique=False,
    )
    op.create_table(
        "aeterna_recovery_otp_challenges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("link_id", sa.UUID(), nullable=False),
        sa.Column("otp_verifier", sa.LargeBinary(), nullable=False),
        sa.Column("otp_key_version", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("resend_after", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("verified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'verified', 'expired', 'locked')",
            name="ck_aeterna_recovery_otp_challenges_status",
        ),
        sa.CheckConstraint(
            "attempt_count BETWEEN 0 AND 5",
            name="ck_aeterna_recovery_otp_challenges_attempt_count",
        ),
        sa.CheckConstraint(
            "octet_length(otp_verifier) = 32",
            name="ck_aeterna_recovery_otp_challenges_verifier_length",
        ),
        sa.CheckConstraint(
            "otp_key_version > 0", name="ck_aeterna_recovery_otp_challenges_key_version"
        ),
        sa.ForeignKeyConstraint(
            ["link_id"], ["aeterna_recovery_claim_links.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aeterna_recovery_otp_challenges_link_id"),
        "aeterna_recovery_otp_challenges",
        ["link_id"],
        unique=False,
    )
    op.add_column(
        "aeterna_email_outbox_events",
        sa.Column("recovery_link_id", sa.UUID(), nullable=True),
    )
    op.add_column(
        "aeterna_email_outbox_events",
        sa.Column("recovery_challenge_id", sa.UUID(), nullable=True),
    )
    op.create_foreign_key(
        "fk_aeterna_email_outbox_events_recovery_challenge",
        "aeterna_email_outbox_events",
        "aeterna_recovery_otp_challenges",
        ["recovery_challenge_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_aeterna_email_outbox_events_recovery_link",
        "aeterna_email_outbox_events",
        "aeterna_recovery_claim_links",
        ["recovery_link_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "ck_aeterna_email_outbox_events_event_type",
        "aeterna_email_outbox_events",
        type_="check",
    )
    op.drop_constraint(
        "ck_aeterna_email_outbox_events_recipient_reference",
        "aeterna_email_outbox_events",
        type_="check",
    )
    op.create_check_constraint(
        "ck_aeterna_email_outbox_events_event_type",
        "aeterna_email_outbox_events",
        "event_type IN ('owner-pre-warning', 'owner-grace-period-started', 'owner-warning-required', 'owner-release-authorized', 'contact-invitation', 'contact-test', 'recovery-claim-link', 'recovery-otp', 'recovery-claimed-owner', 'recovery-claimed-contact')",
    )
    op.create_check_constraint(
        "ck_aeterna_email_outbox_events_recipient_reference",
        "aeterna_email_outbox_events",
        "(recipient_kind = 'owner' AND contact_id IS NULL AND invitation_id IS NULL AND recovery_link_id IS NULL AND recovery_challenge_id IS NULL) OR (recipient_kind = 'contact' AND contact_id IS NOT NULL)",
    )
    op.create_check_constraint(
        "ck_aeterna_email_outbox_events_recovery_link_reference",
        "aeterna_email_outbox_events",
        "(event_type = 'recovery-claim-link' AND recovery_link_id IS NOT NULL) OR (event_type <> 'recovery-claim-link' AND recovery_link_id IS NULL)",
    )
    op.create_check_constraint(
        "ck_aeterna_email_outbox_events_recovery_challenge_reference",
        "aeterna_email_outbox_events",
        "(event_type = 'recovery-otp' AND recovery_challenge_id IS NOT NULL) OR (event_type <> 'recovery-otp' AND recovery_challenge_id IS NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_aeterna_email_outbox_events_recovery_challenge_reference",
        "aeterna_email_outbox_events",
        type_="check",
    )
    op.drop_constraint(
        "ck_aeterna_email_outbox_events_recovery_link_reference",
        "aeterna_email_outbox_events",
        type_="check",
    )
    op.drop_constraint(
        "ck_aeterna_email_outbox_events_recipient_reference",
        "aeterna_email_outbox_events",
        type_="check",
    )
    op.drop_constraint(
        "ck_aeterna_email_outbox_events_event_type",
        "aeterna_email_outbox_events",
        type_="check",
    )
    op.create_check_constraint(
        "ck_aeterna_email_outbox_events_event_type",
        "aeterna_email_outbox_events",
        "event_type IN ('owner-pre-warning', 'owner-grace-period-started', 'owner-warning-required', 'owner-release-authorized', 'contact-invitation', 'contact-test')",
    )
    op.create_check_constraint(
        "ck_aeterna_email_outbox_events_recipient_reference",
        "aeterna_email_outbox_events",
        "(recipient_kind = 'owner' AND contact_id IS NULL AND invitation_id IS NULL) OR (recipient_kind = 'contact' AND contact_id IS NOT NULL)",
    )
    op.drop_constraint(
        "fk_aeterna_email_outbox_events_recovery_challenge",
        "aeterna_email_outbox_events",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_aeterna_email_outbox_events_recovery_link",
        "aeterna_email_outbox_events",
        type_="foreignkey",
    )
    op.drop_column("aeterna_email_outbox_events", "recovery_challenge_id")
    op.drop_column("aeterna_email_outbox_events", "recovery_link_id")
    op.drop_index(
        op.f("ix_aeterna_recovery_otp_challenges_link_id"),
        table_name="aeterna_recovery_otp_challenges",
    )
    op.drop_table("aeterna_recovery_otp_challenges")
    op.drop_index(
        op.f("ix_aeterna_recovery_claim_tokens_grant_id"),
        table_name="aeterna_recovery_claim_tokens",
    )
    op.drop_table("aeterna_recovery_claim_tokens")
    op.drop_index(
        op.f("ix_aeterna_recovery_claim_links_grant_id"),
        table_name="aeterna_recovery_claim_links",
    )
    op.drop_table("aeterna_recovery_claim_links")
    op.drop_index(
        op.f("ix_aeterna_recovery_grants_recovery_id"),
        table_name="aeterna_recovery_grants",
    )
    op.drop_index(
        op.f("ix_aeterna_recovery_grants_contact_id"),
        table_name="aeterna_recovery_grants",
    )
    op.drop_index(
        op.f("ix_aeterna_recovery_grants_account_id"),
        table_name="aeterna_recovery_grants",
    )
    op.drop_table("aeterna_recovery_grants")
    op.drop_index(
        "uq_aeterna_recovery_records_live_device_vault",
        table_name="aeterna_recovery_records",
        postgresql_where=sa.text("state IN ('pending_confirmation', 'sealed')"),
    )
    op.drop_index(
        op.f("ix_aeterna_recovery_records_device_id"),
        table_name="aeterna_recovery_records",
    )
    op.drop_index(
        op.f("ix_aeterna_recovery_records_account_id"),
        table_name="aeterna_recovery_records",
    )
    op.drop_table("aeterna_recovery_records")
    op.drop_index(
        op.f("ix_aeterna_recovery_audit_recovery_id"),
        table_name="aeterna_recovery_audit",
    )
    op.drop_index(
        op.f("ix_aeterna_recovery_audit_contact_id"),
        table_name="aeterna_recovery_audit",
    )
    op.drop_index(
        op.f("ix_aeterna_recovery_audit_account_id"),
        table_name="aeterna_recovery_audit",
    )
    op.drop_table("aeterna_recovery_audit")
    # ### end Alembic commands ###
