"""add account policy concurrency prototype

Revision ID: 3f9e0e028cab
Revises: e69999560f4f
Create Date: 2026-09-21 05:22:06.236742

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f9e0e028cab"
down_revision: Union[str, None] = "e69999560f4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("inactivity_window_seconds", sa.Integer(), nullable=False),
        sa.Column("warning_window_seconds", sa.Integer(), nullable=False),
        sa.Column("grace_window_seconds", sa.Integer(), nullable=False),
        sa.Column("last_activity_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("due_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("state_changed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("warning_started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "owner_warning_proven_at", sa.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column("grace_started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("released_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('ACTIVE', 'PRE_WARNING', 'GRACE_PERIOD', 'RELEASED')",
            name="ck_account_policies_state",
        ),
        sa.CheckConstraint(
            "grace_window_seconds > 0", name="ck_account_policies_grace_window_positive"
        ),
        sa.CheckConstraint(
            "inactivity_window_seconds > 0",
            name="ck_account_policies_inactivity_window_positive",
        ),
        sa.CheckConstraint(
            "warning_window_seconds > 0 AND warning_window_seconds < inactivity_window_seconds",
            name="ck_account_policies_warning_window_valid",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "account_policy_outbox_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_policy_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("from_state", sa.String(length=24), nullable=False),
        sa.Column("to_state", sa.String(length=24), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("scheduled_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processed')",
            name="ck_account_policy_outbox_events_status",
        ),
        sa.ForeignKeyConstraint(
            ["account_policy_id"], ["account_policies.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "idempotency_key", name="uq_account_policy_outbox_events_idempotency_key"
        ),
    )
    op.create_index(
        op.f("ix_account_policy_outbox_events_account_policy_id"),
        "account_policy_outbox_events",
        ["account_policy_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_account_policy_outbox_events_account_policy_id"),
        table_name="account_policy_outbox_events",
    )
    op.drop_table("account_policy_outbox_events")
    op.drop_table("account_policies")
    # ### end Alembic commands ###
