"""add i12 contacts and email delivery

Revision ID: b1e89ccdb30a
Revises: 6b8f7d4a91c2
Create Date: 2026-09-27 07:37:03.086603

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1e89ccdb30a"
down_revision: Union[str, None] = "6b8f7d4a91c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aeterna_recipient_suppressions",
        sa.Column("recipient_lookup", sa.LargeBinary(), nullable=False),
        sa.Column("reason", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IN ('declined', 'hard_bounce', 'complaint', 'abuse')",
            name="ck_aeterna_recipient_suppressions_reason",
        ),
        sa.CheckConstraint(
            "octet_length(recipient_lookup) = 32",
            name="ck_aeterna_recipient_suppressions_lookup_length",
        ),
        sa.PrimaryKeyConstraint("recipient_lookup"),
    )
    op.create_table(
        "aeterna_contacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("email_lookup", sa.LargeBinary(), nullable=False),
        sa.Column("email_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("email_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("email_key_version", sa.Integer(), nullable=False),
        sa.Column("disclosure_mode", sa.String(length=32), nullable=False),
        sa.Column("consent_status", sa.String(length=24), nullable=False),
        sa.Column("invitation_sent_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("declined_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("verified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("bounced_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(consent_status = 'ACCEPTED' AND accepted_at IS NOT NULL AND verified_at IS NOT NULL AND declined_at IS NULL) OR (consent_status = 'DECLINED' AND declined_at IS NOT NULL AND accepted_at IS NULL AND verified_at IS NULL) OR (consent_status IN ('NOT_REQUESTED', 'INVITED') AND accepted_at IS NULL AND declined_at IS NULL AND verified_at IS NULL)",
            name="ck_aeterna_contacts_consent_timestamps",
        ),
        sa.CheckConstraint(
            "consent_status IN ('NOT_REQUESTED', 'INVITED', 'ACCEPTED', 'DECLINED')",
            name="ck_aeterna_contacts_consent_status",
        ),
        sa.CheckConstraint(
            "disclosure_mode IN ('CONFIRM_NOW', 'PRIVATE_UNTIL_RELEASE')",
            name="ck_aeterna_contacts_disclosure_mode",
        ),
        sa.CheckConstraint(
            "email_key_version > 0",
            name="ck_aeterna_contacts_email_key_version_positive",
        ),
        sa.CheckConstraint(
            "octet_length(email_lookup) = 32",
            name="ck_aeterna_contacts_email_lookup_length",
        ),
        sa.CheckConstraint(
            "octet_length(email_nonce) = 12",
            name="ck_aeterna_contacts_email_nonce_length",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["aeterna_accounts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aeterna_contacts_account_id"),
        "aeterna_contacts",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        "uq_aeterna_contacts_active_account_email",
        "aeterna_contacts",
        ["account_id", "email_lookup"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "aeterna_notification_abuse_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("recipient_lookup", sa.LargeBinary(), nullable=True),
        sa.Column("ip_lookup", sa.LargeBinary(), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('contact_create', 'contact_invite', 'contact_test', 'invitation_response')",
            name="ck_aeterna_notification_abuse_events_type",
        ),
        sa.CheckConstraint(
            "ip_lookup IS NULL OR octet_length(ip_lookup) = 32",
            name="ck_aeterna_notification_abuse_events_ip_length",
        ),
        sa.CheckConstraint(
            "recipient_lookup IS NULL OR octet_length(recipient_lookup) = 32",
            name="ck_aeterna_notification_abuse_events_recipient_length",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["aeterna_accounts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_aeterna_notification_abuse_account_time",
        "aeterna_notification_abuse_events",
        ["account_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_aeterna_notification_abuse_ip_time",
        "aeterna_notification_abuse_events",
        ["ip_lookup", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_aeterna_notification_abuse_recipient_time",
        "aeterna_notification_abuse_events",
        ["recipient_lookup", "created_at"],
        unique=False,
    )
    op.create_table(
        "aeterna_notification_audit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("outbox_event_id", sa.UUID(), nullable=True),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_kind IN ('owner', 'recipient', 'system', 'provider')",
            name="ck_aeterna_notification_audit_actor_kind",
        ),
        sa.CheckConstraint(
            "event_type IN ('contact.created', 'contact.invited', 'contact.accepted', 'contact.declined', 'contact.deleted', 'contact.test_queued', 'template.updated', 'delivery.queued', 'delivery.retry_scheduled', 'delivery.provider_accepted', 'delivery.delivered', 'delivery.bounced', 'delivery.complained', 'delivery.failed', 'delivery.cancelled')",
            name="ck_aeterna_notification_audit_event_type",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["aeterna_accounts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aeterna_notification_audit_account_id"),
        "aeterna_notification_audit",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aeterna_notification_audit_contact_id"),
        "aeterna_notification_audit",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aeterna_notification_audit_outbox_event_id"),
        "aeterna_notification_audit",
        ["outbox_event_id"],
        unique=False,
    )
    op.create_table(
        "aeterna_notification_templates",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("owner_message_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("owner_message_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("owner_message_key_version", sa.Integer(), nullable=False),
        sa.Column("contact_message_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("contact_message_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("contact_message_key_version", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "octet_length(owner_message_nonce) = 12 AND octet_length(contact_message_nonce) = 12",
            name="ck_aeterna_notification_templates_nonce_lengths",
        ),
        sa.CheckConstraint(
            "owner_message_key_version > 0 AND contact_message_key_version > 0",
            name="ck_aeterna_notification_templates_key_versions",
        ),
        sa.CheckConstraint(
            "version > 0", name="ck_aeterna_notification_templates_version_positive"
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["aeterna_accounts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_table(
        "aeterna_contact_invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("token_digest", sa.LargeBinary(), nullable=False),
        sa.Column("token_key_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'pending' AND consumed_at IS NULL) OR (status <> 'pending' AND consumed_at IS NOT NULL)",
            name="ck_aeterna_contact_invitations_consumption",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'declined', 'expired', 'revoked')",
            name="ck_aeterna_contact_invitations_status",
        ),
        sa.CheckConstraint(
            "octet_length(token_digest) = 32",
            name="ck_aeterna_contact_invitations_token_digest_length",
        ),
        sa.CheckConstraint(
            "token_key_version > 0",
            name="ck_aeterna_contact_invitations_token_key_version",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["aeterna_contacts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "token_digest", name="uq_aeterna_contact_invitations_token_digest"
        ),
    )
    op.create_index(
        op.f("ix_aeterna_contact_invitations_contact_id"),
        "aeterna_contact_invitations",
        ["contact_id"],
        unique=False,
    )
    op.create_table(
        "aeterna_email_outbox_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("invitation_id", sa.UUID(), nullable=True),
        sa.Column("source_policy_outbox_id", sa.UUID(), nullable=True),
        sa.Column("recipient_kind", sa.String(length=16), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("next_attempt_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("provider_name", sa.String(length=64), nullable=True),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("provider_accepted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("bounced_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("failed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(event_type = 'contact-invitation' AND invitation_id IS NOT NULL) OR (event_type <> 'contact-invitation' AND invitation_id IS NULL)",
            name="ck_aeterna_email_outbox_events_invitation_reference",
        ),
        sa.CheckConstraint(
            "(recipient_kind = 'owner' AND contact_id IS NULL AND invitation_id IS NULL) OR (recipient_kind = 'contact' AND contact_id IS NOT NULL)",
            name="ck_aeterna_email_outbox_events_recipient_reference",
        ),
        sa.CheckConstraint(
            "event_type IN ('owner-pre-warning', 'owner-grace-period-started', 'owner-warning-required', 'owner-release-authorized', 'contact-invitation', 'contact-test')",
            name="ck_aeterna_email_outbox_events_event_type",
        ),
        sa.CheckConstraint(
            "recipient_kind IN ('owner', 'contact')",
            name="ck_aeterna_email_outbox_events_recipient_kind",
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'sending', 'retry_pending', 'provider_accepted', 'delivered', 'bounced', 'complained', 'ambiguous', 'failed', 'cancelled')",
            name="ck_aeterna_email_outbox_events_status",
        ),
        sa.CheckConstraint(
            "attempt_count >= 0",
            name="ck_aeterna_email_outbox_events_attempt_count_nonnegative",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["aeterna_accounts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["aeterna_contacts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["invitation_id"], ["aeterna_contact_invitations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_policy_outbox_id"],
            ["account_policy_outbox_events.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "idempotency_key", name="uq_aeterna_email_outbox_events_idempotency_key"
        ),
    )
    op.create_index(
        op.f("ix_aeterna_email_outbox_events_account_id"),
        "aeterna_email_outbox_events",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aeterna_email_outbox_events_contact_id"),
        "aeterna_email_outbox_events",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        "ix_aeterna_email_outbox_events_dispatch",
        "aeterna_email_outbox_events",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_index(
        "uq_aeterna_email_outbox_events_provider_message",
        "aeterna_email_outbox_events",
        ["provider_name", "provider_message_id"],
        unique=True,
        postgresql_where=sa.text("provider_message_id IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_aeterna_email_outbox_events_source_policy_outbox_id"),
        "aeterna_email_outbox_events",
        ["source_policy_outbox_id"],
        unique=False,
    )
    op.create_table(
        "aeterna_email_delivery_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("outbox_event_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("provider_name", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('sending', 'retryable_failure', 'ambiguous_failure', 'failed', 'provider_accepted')",
            name="ck_aeterna_email_delivery_attempts_status",
        ),
        sa.ForeignKeyConstraint(
            ["outbox_event_id"], ["aeterna_email_outbox_events.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "outbox_event_id",
            "attempt_number",
            name="uq_aeterna_email_delivery_attempts_event_number",
        ),
    )
    op.create_index(
        op.f("ix_aeterna_email_delivery_attempts_outbox_event_id"),
        "aeterna_email_delivery_attempts",
        ["outbox_event_id"],
        unique=False,
    )
    op.create_table(
        "aeterna_email_delivery_callbacks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("outbox_event_id", sa.UUID(), nullable=False),
        sa.Column("provider_name", sa.String(length=64), nullable=False),
        sa.Column("callback_id", sa.String(length=255), nullable=False),
        sa.Column("callback_type", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("received_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "callback_type IN ('provider_accepted', 'delivered', 'bounced', 'complained', 'rejected')",
            name="ck_aeterna_email_delivery_callbacks_type",
        ),
        sa.ForeignKeyConstraint(
            ["outbox_event_id"], ["aeterna_email_outbox_events.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider_name",
            "callback_id",
            name="uq_aeterna_email_delivery_callbacks_provider_callback",
        ),
    )
    op.create_index(
        op.f("ix_aeterna_email_delivery_callbacks_outbox_event_id"),
        "aeterna_email_delivery_callbacks",
        ["outbox_event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_aeterna_email_delivery_callbacks_outbox_event_id"),
        table_name="aeterna_email_delivery_callbacks",
    )
    op.drop_table("aeterna_email_delivery_callbacks")
    op.drop_index(
        op.f("ix_aeterna_email_delivery_attempts_outbox_event_id"),
        table_name="aeterna_email_delivery_attempts",
    )
    op.drop_table("aeterna_email_delivery_attempts")
    op.drop_index(
        op.f("ix_aeterna_email_outbox_events_source_policy_outbox_id"),
        table_name="aeterna_email_outbox_events",
    )
    op.drop_index(
        "uq_aeterna_email_outbox_events_provider_message",
        table_name="aeterna_email_outbox_events",
        postgresql_where=sa.text("provider_message_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_aeterna_email_outbox_events_dispatch",
        table_name="aeterna_email_outbox_events",
    )
    op.drop_index(
        op.f("ix_aeterna_email_outbox_events_contact_id"),
        table_name="aeterna_email_outbox_events",
    )
    op.drop_index(
        op.f("ix_aeterna_email_outbox_events_account_id"),
        table_name="aeterna_email_outbox_events",
    )
    op.drop_table("aeterna_email_outbox_events")
    op.drop_index(
        op.f("ix_aeterna_contact_invitations_contact_id"),
        table_name="aeterna_contact_invitations",
    )
    op.drop_table("aeterna_contact_invitations")
    op.drop_table("aeterna_notification_templates")
    op.drop_index(
        op.f("ix_aeterna_notification_audit_outbox_event_id"),
        table_name="aeterna_notification_audit",
    )
    op.drop_index(
        op.f("ix_aeterna_notification_audit_contact_id"),
        table_name="aeterna_notification_audit",
    )
    op.drop_index(
        op.f("ix_aeterna_notification_audit_account_id"),
        table_name="aeterna_notification_audit",
    )
    op.drop_table("aeterna_notification_audit")
    op.drop_index(
        "ix_aeterna_notification_abuse_recipient_time",
        table_name="aeterna_notification_abuse_events",
    )
    op.drop_index(
        "ix_aeterna_notification_abuse_ip_time",
        table_name="aeterna_notification_abuse_events",
    )
    op.drop_index(
        "ix_aeterna_notification_abuse_account_time",
        table_name="aeterna_notification_abuse_events",
    )
    op.drop_table("aeterna_notification_abuse_events")
    op.drop_index(
        "uq_aeterna_contacts_active_account_email",
        table_name="aeterna_contacts",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_aeterna_contacts_account_id"), table_name="aeterna_contacts")
    op.drop_table("aeterna_contacts")
    op.drop_table("aeterna_recipient_suppressions")
    # ### end Alembic commands ###
